#!/usr/bin/bash

case $1 in
    shutdown)
        systemctl poweroff
        ;;
    reboot)
        systemctl reboot
        ;;
    suspend)
        hyprctl dispatch dpms off & hyprlock & sleep 8 && systemctl suspend
        ;;
    lock)
        loginctl lock-session
        ;;
    *)
        echo "error"
esac
